% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Exploring Pediatric Appendicitis},
  pdfauthor={Muhammad Alakhdar},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Exploring Pediatric Appendicitis}
\author{Muhammad Alakhdar}
\date{2025-02-13}

\begin{document}
\maketitle

\section{Introdution}\label{introdution}

\href{https://doi.org/10.1016/S0140-6736(16)31012-1}{In 2015,
approximately 11.6 million cases of appendicitis were reported,
resulting in approximately 50,100 deaths worldwide}, deaths could be
attributed to many reasons, such as lack of access to medicine, quality
of care, and medical diagnostic error.

Helping healthcare professionals make more informed decisions is one way
to reduce diagnostic errors.

There are many criteria to do this, such as history taking, physical
examination, risk scores (e.g., Alvarado score), and imaging techniques
such as ultrasound and CT.

The accuracy of the diagnosis could be improved, for example, by using
machine learning. \href{https://doi.org/10.1016/j.media.2023.103042}{A
recent study built a model to predict appendicitis in pediatrics using
an interpretable unsupervised machine learning method}.

\href{https://doi.org/10.5281/zenodo.7711412}{Since a lot of models have
been built using just history and physical examinin as predictors, we
would use the same dataset to explore the disease for a bit then build
models that focus on ultrasonography as a way to diagnose appendicitis.}

\section{Methodology}\label{methodology}

\href{https://doi.org/10.5281/zenodo.7711412}{The dataset was acquired
in a retrospective study from a cohort of pediatric patients admitted
with abdominal pain to Children's Hospital St.~Hedwig in Regensburg,
Germany.}

\begin{itemize}
\tightlist
\item
  Taking a look at the dataset
\end{itemize}

\begin{verbatim}
## Rows: 776
## Columns: 5
## $ Sex          <chr> "female", "male", "female", "female", "female", "male", "~
## $ US_Performed <chr> "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "~
## $ Severity     <chr> "uncomplicated", "uncomplicated", "uncomplicated", "uncom~
## $ Management   <chr> "conservative", "conservative", "conservative", "conserva~
## $ Diagnosis    <chr> "appendicitis", "no appendicitis", "no appendicitis", "no~
\end{verbatim}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1045}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1940}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2090}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2537}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2388}}@{}}
\caption{First Ten Rows of the Pediatric Patients
Dataset}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Sex
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
US\_Performed
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Severity
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Management
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Diagnosis
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Sex
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
US\_Performed
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Severity
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Management
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Diagnosis
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
female & yes & uncomplicated & conservative & appendicitis \\
male & yes & uncomplicated & primary surgical & appendicitis \\
male & yes & complicated & primary surgical & appendicitis \\
female & yes & uncomplicated & conservative & no appendicitis \\
female & yes & uncomplicated & conservative & no appendicitis \\
female & yes & uncomplicated & conservative & no appendicitis \\
male & yes & uncomplicated & conservative & no appendicitis \\
male & yes & uncomplicated & primary surgical & appendicitis \\
male & yes & uncomplicated & primary surgical & appendicitis \\
female & yes & uncomplicated & conservative & appendicitis \\
\end{longtable}

\begin{verbatim}
## Number of missing values is 14008
\end{verbatim}

\subsection{Some Plots}\label{some-plots}

\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/A histogram for the age-1} 

}

\caption{Distribution of the Patients's Age by Gender}\label{fig:A histogram for the age}
\end{figure}

\begin{longtable}[t]{lr}
\caption{\label{tab:A histogram for the age}The Mean Age of Patients By Gender}\\
\toprule
Sex & Mean\\
\midrule
\cellcolor{gray!10}{female} & \cellcolor{gray!10}{12.06}\\
male & 10.68\\
\bottomrule
\end{longtable}

\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/A Bar plot for the Diagnosis-1} 

}

\caption{Prevalence of Appendicitis by Gender}\label{fig:A Bar plot for the Diagnosis}
\end{figure}

\begin{longtable}[]{@{}llrr@{}}
\caption{Prevalence of Appendicitis by Gender}\tabularnewline
\toprule\noalign{}
Sex & Diagnosis & n & p \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Sex & Diagnosis & n & p \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
female & appendicitis & 200 & 0.53 \\
female & no appendicitis & 176 & 0.47 \\
male & appendicitis & 262 & 0.65 \\
male & no appendicitis & 141 & 0.35 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  Figure 2 shows that the prevalence in appendicitis is more males than
  females, which is consistent with existing findings, but it is not
  that substantial.
\end{itemize}

\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/unnamed-chunk-6-1} 

}

\caption{Alvarado Risk Score .vs Appendicitis Diagnosis}\label{fig:unnamed-chunk-6}
\end{figure}

\begin{longtable}[]{@{}lrr@{}}
\caption{Alvarado Risk Score .vs Appendicitis Diagnosis}\tabularnewline
\toprule\noalign{}
Diagnosis & mean & median \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Diagnosis & mean & median \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
appendicitis & 6.67 & 7 \\
no appendicitis & 4.83 & 5 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  Alvarado score is a system that have been developed to identify people
  who are likely to have appendicitis, as a score below 5 suggests
  against a diagnosis of appendicitis, while a score of 7 or more is
  predictive of acute appendicitis, but it is performance varies. Here,
  the severity of the diagnosis was added to see if the score also
  differed.
\end{itemize}

\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/unnamed-chunk-7-1} 

}

\caption{Appendix Diameter .vs Appendicitis Type of Management}\label{fig:unnamed-chunk-7-1}
\end{figure}
\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/unnamed-chunk-7-2} 

}

\caption{Appendix Diameter .vs Appendicitis Type of Management}\label{fig:unnamed-chunk-7-2}
\end{figure}

\begin{longtable}[]{@{}lrr@{}}
\caption{Mean of Appendix Diameter By Appendicitis
Management}\tabularnewline
\toprule\noalign{}
Diagnosis & mean & median \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Diagnosis & mean & median \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
appendicitis & 8.70 & 8.2 \\
no appendicitis & 5.04 & 5.0 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  \textbackslash begin\{figure\}
\end{itemize}

\{\centering \includegraphics{PediaAppendicitis_files/figure-latex/Severity of the appendicits-1}

\}

\caption{Severity of Appendicitis .vs Appendicular Abscess  }\label{fig:Severity of the appendicits}

\textbackslash end\{figure\}

\begin{itemize}
\tightlist
\item
  In severe cases, abscess can be seen and Figure 4 shows that the
  proportion is higher for complicated cases.
\end{itemize}

\subsection{Statistical Analysis}\label{statistical-analysis}

\subsubsection{Hypothesis testing}\label{hypothesis-testing}

\begin{itemize}
\tightlist
\item
  Since the use of ultrasound is less expensive and less harmful than
  CT, it streamlines the diagnostic process.
\end{itemize}

Here we will test if the addition of \textbf{appendiceal diameter} will
have a discernible difference on the outcome of the diagnosis, the
method we will use is hypothesis testing with \textbf{randomization}.

The two populations of interest in this study are pediatric patients who
do or do not have appendicitis.

\emph{Let} \(p\) *= the true mean of appendix diameter in pediatric
patients.

\begin{itemize}
\tightlist
\item
  So our hypotheses are
\end{itemize}

\(H_0: p_{Appendicitis} = p_{no~Appendicitis}\)

\(H_A: p_{Appendicitis} \ne p_{no~Appendicitis}\)

\begin{itemize}
\tightlist
\item
  With a p-value of 0, which is smaller than the discernability level of
  0.05, we reject the null hypothesis. The data provide convincing
  evidence that there is a difference between the mean appendix
  diameters of pediatric patients with and without appendicitis.
\end{itemize}

\begin{longtable}[]{@{}rr@{}}
\caption{95\% confidence interval for the difference in mean between
patients diagnosed with appendicitis or no appendicitis.}\tabularnewline
\toprule\noalign{}
lower\_ci & upper\_ci \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
lower\_ci & upper\_ci \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
3.37 & 3.94 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  \emph{We are 95\% confident that the mean diameter of the appendix in
  pediatric patients with ``appendicitis'' is 3.37 to 3.94 greater than
  in pediatric patients without appendicitis..}
\end{itemize}

\subsubsection{Modeling}\label{modeling}

\begin{itemize}
\tightlist
\item
  To help the health workers make more informed decisions (i.e,
  Accurately diagnosing the appendicitis) we would use machine learning.
\end{itemize}

We will build Supervised explainable models like logistic regression
then test and validate the model.

So we will use \textbf{cross validation} as way to build the model then
we would use \textbf{ROC} to check the models precision and accuracy.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2571}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2143}}@{}}
\caption{A Model to Diagnose Appendicitis With Avarado
Score}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
pred\_class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pred\_appendicitis
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pred\_no\_appendicitis
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
alvarado\_score
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
pred\_class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pred\_appendicitis
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pred\_no\_appendicitis
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
alvarado\_score
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
appendicitis & 0.78 & 0.22 & 6 \\
appendicitis & 0.95 & 0.05 & 9 \\
appendicitis & 0.68 & 0.32 & 5 \\
appendicitis & 0.86 & 0.14 & 7 \\
appendicitis & 0.56 & 0.44 & 4 \\
appendicitis & 0.56 & 0.44 & 4 \\
appendicitis & 0.78 & 0.22 & 6 \\
no appendicitis & 0.30 & 0.70 & 2 \\
appendicitis & 0.86 & 0.14 & 7 \\
appendicitis & 0.86 & 0.14 & 7 \\
\end{longtable}

\begin{longtable}[]{@{}llrrl@{}}
\caption{Precision and Accuracy of Model to Diagnose Appendicitis With
Avarado Score}\tabularnewline
\toprule\noalign{}
.pred\_class & Diagnosis & n & p & decision \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
.pred\_class & Diagnosis & n & p & decision \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
appendicitis & appendicitis & 67 & 0.96 & True positive \\
no appendicitis & appendicitis & 3 & 0.04 & False negative \\
appendicitis & no appendicitis & 14 & 0.61 & False positive \\
no appendicitis & no appendicitis & 9 & 0.39 & True negative \\
\end{longtable}

\begin{center}\includegraphics{PediaAppendicitis_files/figure-latex/model eval0-1} \end{center}

\begin{longtable}[]{@{}lrr@{}}
\caption{A Model to Diagnose Appendicitis With Avarado Score,
Appendix\_Diameter, Weight and BMI}\tabularnewline
\toprule\noalign{}
pred\_class & pred\_appendicitis & pred\_no\_appendicitis \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
pred\_class & pred\_appendicitis & pred\_no\_appendicitis \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
no appendicitis & 0.01 & 0.99 \\
no appendicitis & 0.10 & 0.90 \\
no appendicitis & 0.29 & 0.71 \\
appendicitis & 0.80 & 0.20 \\
appendicitis & 0.96 & 0.04 \\
no appendicitis & 0.46 & 0.54 \\
appendicitis & 1.00 & 0.00 \\
no appendicitis & 0.03 & 0.97 \\
appendicitis & 0.85 & 0.15 \\
appendicitis & 1.00 & 0.00 \\
\end{longtable}

\begin{longtable}[]{@{}llrrl@{}}
\caption{Precision and Accuracy of Model to Diagnose Appendicitis With
Avarado Score, Appendix\_Diameter, Weight and BMI}\tabularnewline
\toprule\noalign{}
.pred\_class & Diagnosis & n & p & decision \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
.pred\_class & Diagnosis & n & p & decision \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
appendicitis & appendicitis & 67 & 0.96 & True positive \\
no appendicitis & appendicitis & 3 & 0.04 & False negative \\
no appendicitis & no appendicitis & 23 & 1.00 & True negative \\
\end{longtable}

\begin{center}\includegraphics{PediaAppendicitis_files/figure-latex/model eval-1} \end{center}

\begin{figure}

{\centering \includegraphics{PediaAppendicitis_files/figure-latex/Comparing models-1} 

}

\caption{Comparing the Accuracy and Precision of both Models}\label{fig:Comparing models}
\end{figure}

\begin{itemize}
\tightlist
\item
  The second model that used \textbf{Ultra-sonography} results showed
  lower \textbf{False positives and negatives}. per table above.
\end{itemize}

\subsubsection{Diagnosing}\label{diagnosing}

\begin{verbatim}
## # A tibble: 1 x 2
##   .pred_appendicitis `.pred_no appendicitis`
##                <dbl>                   <dbl>
## 1               1.00                0.000358
\end{verbatim}

\end{document}
